### ISSUE TITLE
Mudança de ambiente de desenvolvimento

### ISSUE THREAD

**Issue by krelod** [GabrielZarpellon/omoriptbr#45]
Por que vocês estão usando HTML ao invés de usar NodeJS nesse projeto?

**Comment by GabrielZarpellon** [comment]
> Por que vocês estão usando HTML ao invés de usar NodeJS nesse projeto?

Não é muito comum usar NodeJS em mods de jogo, não sei se seria viável. Grande parte do jogo é feita em javascript e criptografada, então o mod é feito da mesma forma, só que descriptografado e utilizando um modloader que lê os arquivos. 
O único problema é o quão pesado está ficando a pasta do mod, então algumas pessoas estão tendo problemas com isso.

**Comment by krelod** [comment]
O que está levando o mod a ficar pesado?

**Comment by GabrielZarpellon** [comment]
> O que está levando o mod a ficar pesado?

A quantidade de arquivos. O mod basicamente traduz grande parte dos arquivos do jogo, então é quase como se duplicasse o peso do jogo
